disabled_rules:
 - todo
 - line_length
 - identifier_name
 - multiple_closures_with_trailing_closure
 - force_try
 - weak_delegate
# Not really sure about a bunch of these, just turning most stuff in the 'performance' and 'lint' categories
opt_in_rules:
 - unowned_variable_capture
 - array_init
 - identical_operands
 - overridden_super_call
 - override_in_extension
 - private_action
 - private_outlet
 - prohibited_interface_builder
 - prohibited_super_call
 - quick_discouraged_call
 - required_enum_case
 - strong_iboutlet
 - contains_over_filter_count
 - contains_over_filter_is_empty
 - contains_over_first_not_nil
 - contains_over_range_nil_comparison
 - empty_collection_literal
 - empty_count
 - empty_string
 - first_where
 - flatmap_over_map_reduce
 - last_where
 - reduce_into
 - sorted_first_last
